# Generated by Django 4.2 on 2023-04-08 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Machine_name_Mealy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Machine_name_Moore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Moore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("q", models.CharField(max_length=200)),
                ("fq0", models.CharField(max_length=200)),
                ("fq1", models.CharField(max_length=200)),
                ("gq0", models.CharField(max_length=200)),
                ("gq1", models.CharField(max_length=200)),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="StateMachine.machine_name_moore",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mealy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("q", models.CharField(max_length=200)),
                ("fq0", models.CharField(max_length=200)),
                ("fq1", models.CharField(max_length=200)),
                ("hq", models.CharField(max_length=200)),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="StateMachine.machine_name_mealy",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="machine_name_moore",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_name_Moore"
            ),
        ),
        migrations.AddConstraint(
            model_name="machine_name_mealy",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_name_Mealy"
            ),
        ),
        migrations.AddConstraint(
            model_name="moore",
            constraint=models.UniqueConstraint(
                fields=("q",), name="unique_name_Moore_State"
            ),
        ),
        migrations.AddConstraint(
            model_name="mealy",
            constraint=models.UniqueConstraint(
                fields=("q",), name="unique_name_Mealy_State"
            ),
        ),
    ]
