# Generated by Django 4.2 on 2023-04-09 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("StateMachine", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mealy",
            name="unique_name_Mealy_State",
        ),
    ]
