# Generated by Django 4.2 on 2023-04-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StateMachine", "0002_remove_mealy_unique_name_mealy_state"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="moore",
            name="unique_name_Moore_State",
        ),
        migrations.RenameField(
            model_name="mealy",
            old_name="hq",
            new_name="gq0",
        ),
        migrations.RenameField(
            model_name="moore",
            old_name="gq0",
            new_name="hq",
        ),
        migrations.RemoveField(
            model_name="moore",
            name="gq1",
        ),
        migrations.AddField(
            model_name="mealy",
            name="gq1",
            field=models.CharField(default="a", max_length=200),
            preserve_default=False,
        ),
    ]
