# Generated by Django 4.2 on 2023-04-07 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Mealy", "0004_machine_name_remove_mealy_unique_name_mealu_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Machine_name",
            new_name="Machine_name_Mealy",
        ),
    ]
