# Generated by Django 4.2 on 2023-04-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Mealy", "0005_rename_machine_name_machine_name_mealy"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="mealy",
            constraint=models.UniqueConstraint(
                fields=("q",), name="unique_name_Mealy_State"
            ),
        ),
    ]
