# Generated by Django 4.2 on 2023-04-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Moore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("q", models.CharField(max_length=200)),
                ("fq0", models.CharField(max_length=200)),
                ("fq1", models.CharField(max_length=200)),
                ("gq0", models.CharField(max_length=200)),
                ("gq1", models.CharField(max_length=200)),
            ],
        ),
    ]
