# Generated by Django 4.2 on 2023-04-07 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Moore", "0002_moore_unique_name_moore"),
    ]

    operations = [
        migrations.CreateModel(
            name="Machine_name",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="moore",
            name="unique_name_Moore",
        ),
        migrations.AddConstraint(
            model_name="machine_name",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_name_Moore"
            ),
        ),
        migrations.AlterField(
            model_name="moore",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Moore.machine_name"
            ),
        ),
    ]
