# Generated by Django 4.2 on 2023-04-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Moore", "0004_rename_machine_name_machine_name_moore"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="moore",
            constraint=models.UniqueConstraint(
                fields=("q",), name="unique_name_Moore_State"
            ),
        ),
    ]
